services:
  kikileharani.tournament.listener:
    class: kikileharani\tournament\event\listener
    arguments:
      - '@dbal.conn'
      - '@user'
    tags:
      - { name: event.listener }

  kikileharani.tournament.controller:
    class: kikileharani\tournament\controller\tournament_controller
    arguments:
      - '@template'
      - '@user'
      - '@auth'
      - '@dbal.conn'
      - '@language'

  kikileharani.tournament.acp.controller:
    class: kikileharani\tournament\controller\acp_tournament_controller
    arguments:
      - '@template'
      - '@user'
      - '@auth'
      - '@dbal.conn'
      - '@request'
      - '@log'
