services:
  kikileharani.tournament.listener:
    class: kikileharani\tournament\event\listener
    arguments:
      - '@dbal.conn'
      - '@user'
      - '@config'
    tags:
      - { name: event.listener }

  kikileharani.tournament.controller:
    class: kikileharani\tournament\controller\tournament_controller
    arguments:
      - '@controller.helper'
      - '@template'
      - '@user'
      - '@auth'
      - '@dbal.conn'
      - '@config'
